# dTE Correlation Plot between Vero and HBEC #

# The following correlation pairs are plotted:
# Vero 2hpi vs. HBEC 24hpi; Vero 6hpi vs. HBEC 48hpi; Vero 12hpi vs. HBEC 72hpi; Vero 24hpi vs. HBEC 96hpi.
# ISGs are taken from rseq logFC vs. dTE plots.
# dTE values are taken from dTE tables generated by calcTE2.R.


library(dplyr)
library(ggplot2)
library(ggrepel)


## Vero ISGs ##
Vero_2hpi <- c("EGR3", "NFKBIA", "FOSB")

Vero_6hpi <- c("CXCL11", "CXCL3", "CXCL1", "IFIT1", "EGR1", "TNFAIP3")

Vero_12hpi <- c("CXCL11", "OASL", "NR4A3", "IFNL1", "CXCL8", "NFKBIA",
                 "CXCL3", "MX1", "CCL5", "CXCL1", "IFIT1", "IFIT2", "IFIT3",
                 "USP18", "IL1A", "IRF1", "ISG15", "IFIT5")

Vero_24hpi <- c("NR4A3", "OASL", "FOS", "CXCL8", "CXCL11", "NFKBIA",
                 "CXCL3", "IFI44", "ISG15", "EGR1", "EGR2", "IFIT1",
                 "IFIT2", "IFIT3", "CXCR4", "IL6", "IRF1", "IL11")


## HBEC ISGs ##
HBEC_24hpi <- c("OASL", "CXCL11", "CXCL10", "MX2", "ISG15", "IFI27",
                 "CXCL9", "RSAD2", "IFI6", "OAS3", "CMPK2", "HELZ2",
                 "IDO1", "CCL2", "OAS1", "IFIT1", "IFIT2", "IFIT3")

HBEC_48hpi <- c("CXCL10", "CXCL11", "OASL", "CXCL9", "MX2", "IFNB1",
                 "CMPK2", "OAS3", "IFIT1", "IFI44L", "IFIT2", "IFI44",
                 "OAS1", "IFI6", "IFIT3", "STAT2", "MX1", "ISG15", "IDO1")

HBEC_72hpi <- c("CXCL10", "OASL", "CXCL9", "IFNB1", "MX2", "IFNL1",
                 "OAS3", "CXCL11", "CXCL6", "RSAD2", "IFIT2", "IFIT1",
                 "OAS1", "IFIT3", "CMPK2", "OAS2", "IL8", "MX1",
                 "IDO1", "IFI44", "IFI6", "IFI44L", "ISG15", "STAT1",
                 "STAT2", "CXCL2", "NR4A1", "EGR3", "NR4A3")

HBEC_96hpi <- c("IFI6", "XAF1", "IFITM1", "IFI44L", "AIM2", "OAS1",
                 "IFI44", "CCL20", "IFIT1", "OAS2", "OAS3", "IFIH1",
                 "IFIT3", "CMPK2", "OASL", "IDO1", "ISG15", "IFNL1",
                 "MX2", "IFIT5", "IL6", "CXCL11", "CXCL12", "CXCL3",
                 "CXCL6", "CXCL9", "CXCL2", "SELL", "CARD17", "NOS2", "TNFAIP6")



# Directory path to HBEC and Vero dTE tables.
# Files should be named as "[experiment]_[timepoint]_dTE.csv".
# For example, "HBEC_24hpi_dTE.csv".
dTE_path <- "/path/to/dTE_tables"
outpath <- "/output/path/to/save/plots"



set1 <- union(Vero_2hpi, HBEC_24hpi)
set2 <- union(Vero_6hpi, HBEC_48hpi)
set3 <- union(Vero_12hpi, HBEC_72hpi)
set4 <- union(Vero_24hpi, HBEC_96hpi)


# Only uncomment and run one of the following code blocks at a time. #

### START ###
# gs <- set1
# Vero_tp <- "2hpi"
# HBEC_tp <- "24hpi"

# gs <- set2
# Vero_tp <- "6hpi"
# HBEC_tp <- "48hpi"

# gs <- set3
# Vero_tp <- "12hpi"
# HBEC_tp <- "72hpi"

# gs <- set4
# Vero_tp <- "24hpi"
# HBEC_tp <- "96hpi"
### END ###



Vero_dTE_table <- read.csv(file = file.path(dTE_path, paste0("Vero_", Vero_tp, "_dTE.csv")))
HBEC_dTE_table <- read.csv(file = file.path(dTE_path, paste0("HBEC_", HBEC_tp, "_dTE.csv")))
Vero_dTE <- Vero_dTE_table[match(gs, Vero_dTE_table$X), c("X", "delta_te")]
HBEC_dTE <- HBEC_dTE_table[match(gs, HBEC_dTE_table$X), c("X", "delta_te")]

com_table <- full_join(Vero_dTE, HBEC_dTE, by = "X", suffix = c("_Vero", "_HBEC"))
com_table <- na.omit(com_table)




### PLOTTING ###

p <- ggplot(data = com_table, mapping = aes(x = delta_te_Vero, y = delta_te_HBEC, label = X)) +
  geom_point(size = 1.5, color = "blue", alpha = 0.5) +
  geom_text_repel(size = 3) +
  xlab(label = paste0("Vero ", Vero_tp, " dTE")) +
  ylab(label = paste0("HBEC ", HBEC_tp, " dTE")) +
  theme_classic()

png(filename = file.path(outpath, paste("Vero", Vero_tp, "HBEC", HBEC_tp, "cor.png", sep = "_")),
    height = 1500, width = 1500, res = 300)
print(p)
dev.off()

